// generated by stringer -type=Key; DO NOT EDIT

package keys

import "fmt"

const _Key_name = "F1F2F3F4F5F6F7F8F9F10F11F12InsertDeleteHomeEndUpDownLeftRightPgDnPgUpBackspaceTabEnterEsc"

var _Key_index = [...]uint8{2, 4, 6, 8, 10, 12, 14, 16, 18, 21, 24, 27, 33, 39, 43, 46, 48, 52, 56, 61, 65, 69, 78, 81, 86, 89}

func (i Key) String() string {
	i -= 1114111
	if i < 0 || i >= Key(len(_Key_index)) {
		return fmt.Sprintf("Key(%d)", i+1114111)
	}
	hi := _Key_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Key_index[i-1]
	}
	return _Key_name[lo:hi]
}
