// generated by stringer -type=Modifier; DO NOT EDIT

package keys

import "fmt"

const (
	_Modifier_name_0 = "ShiftCtrl"
	_Modifier_name_1 = "Alt"
)

var (
	_Modifier_index_0 = [...]uint8{5, 9}
	_Modifier_index_1 = [...]uint8{3}
)

func (i Modifier) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		lo := uint8(0)
		if i > 0 {
			lo = _Modifier_index_0[i-1]
		}
		return _Modifier_name_0[lo:_Modifier_index_0[i]]
	case i == 4:
		return _Modifier_name_1
	default:
		return fmt.Sprintf("Modifier(%d)", i)
	}
}
